# Generated by Django 4.2.16 on 2024-09-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='sea_level_p_avg_inches',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='sea_level_p_high_inches',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='sea_level_p_low_inches',
            field=models.FloatField(),
        ),
    ]
