# Generated by Django 4.2.16 on 2024-09-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temp_high_f', models.IntegerField()),
                ('temp_avg_f', models.IntegerField()),
                ('temp_low_f', models.IntegerField()),
                ('dew_point_high_f', models.IntegerField()),
                ('dew_point_avg_f', models.IntegerField()),
                ('dew_point_low_f', models.IntegerField()),
                ('humidity_high_percent', models.FloatField()),
                ('humidity_avg_percent', models.FloatField()),
                ('humidity_low_percent', models.FloatField()),
                ('sea_level_p_high_inches', models.IntegerField()),
                ('sea_level_p_avg_inches', models.IntegerField()),
                ('sea_level_p_low_inches', models.IntegerField()),
                ('events', models.CharField(max_length=300)),
            ],
        ),
    ]
