# Generated by Django 4.2.9 on 2024-10-20 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diaries', '0002_diary_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='like_users',
            field=models.ManyToManyField(related_name='like_diaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
