# Generated by Django 4.2.11 on 2024-09-21 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='additional_info',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='api_url',
            field=models.URLField(validators=[django.core.validators.MinLengthValidator(15, '15글자 이상 입력해야합니다.'), django.core.validators.MaxLengthValidator(60, '60글자 이하로 입력해야 합니다.'), django.core.validators.URLValidator()]),
        ),
    ]
