# Generated by Django 4.2.11 on 2024-10-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malls', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='customer_product',
            new_name='buy_list',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
